--- 
title: "OHI Global Assessment Guide"
author: "OHI Team"
date: '`r Sys.Date()`'
bibliography:
- book.bib
- packages.bib
description: A guide for conducting the OHI Global Assessment
documentclass: book
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
---

# Overview {#Overview}

This guide is a resource for calculating the annual Ocean Health Index global assessments. It is intended for use by OHI fellows and anyone interested in the process of how scores are calculated, but only those with access to the internal server (Mazu) are able to actually perform the assessment. 

By conducting a yearly assessment, the OHI delivers information about a suite of goals important to humans and our use of the oceans. The OHI methods are reproducible and ever-evolving, so updates to this guide are welcomed as improvements and upgrades are incorporated.


*Content covered in the following chapters includes:*

* How to initialize a new assessment
* Thorough instructions for data prep, including how to:
  * Access and organize files
  * Structure data prep scripts
  * Gapfill data
  * Check results
* Update data layers to OHI global and recalculate scores
* Finalize the assessment, including how to:
  * Review scores
  * Create bibliography
  * Update metadata
  * Create methods and results documents
  * Upload to repository





## Repositories used to calculate the global assessment

<!--- TODO Gage add important fig here (just kidding this is just an example)  --->

* *ohiprep_v20??* Scripts and intermediate files used to prepare the data layers used by the OHI model.

* *ohi-global* Data layers, supplementary information, models, and scripts used to calculate the global scores.

* *ohicore* An R package that includes the core functions used in all assessments. See [package description](http://ohi-science.org/ohicore/) for more information.


*Table describing ohiprep_v20?? contents*
(NOTE: suffix of repo name is the year of the assessment)

folder      |      description
------------| ------------------------------
globalprep  | scripts used to prepare all goal, pressure, and resilience data layers (description of file organization)
Reference   | handy reference materials used throughout the global assessmeent
workflow    | Rmd templates, sourced files, and functions used throughout data preparation


*Table describing ohi-global contents*
(NOTE: this describes only the most relevant folders/files)

folder      |     description
------------| ------------------------------
eez  |   global models and data
     layers | data layers used in the models (data are copied from ohiprep using paths from eez_layers_meta_data/layers_eez_base.csv)
     conf   | models and supplementary data used to calculate scores
     calculate_scores.R | master script used to calculate scores
     scores.csv | score output from calculate_scores.R (includes all score dimensions for each goal and country)
eez_layers_meta_data | csv files describing data layers
global_supplement | files used to create OHI methods document
yearly_results | reporting on results of each year's OHI assessment

