<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Data Prep | OHI Global Assessment Guide</title>
  <meta name="description" content="A guide for conducting the OHI Global Assessment" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Data Prep | OHI Global Assessment Guide" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A guide for conducting the OHI Global Assessment" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Data Prep | OHI Global Assessment Guide" />
  
  <meta name="twitter:description" content="A guide for conducting the OHI Global Assessment" />
  

<meta name="author" content="OHI Team" />


<meta name="date" content="2023-06-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="starting-a-new-year.html"/>
<link rel="next" href="updating-scores.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">OHI Global Guide</a></li>

<li class="divider"></li>
<li><a href="index.html#Overview" id="toc-Overview"><span class="toc-section-number">1</span> Overview</a>
<ul>
<li><a href="index.html#repositories-used-to-calculate-the-global-assessment" id="toc-repositories-used-to-calculate-the-global-assessment"><span class="toc-section-number">1.1</span> Repositories used to calculate the global assessment</a>
<ul>
<li><a href="index.html#ohiprep_v20" id="toc-ohiprep_v20"><span class="toc-section-number">1.1.1</span> ohiprep_v20??</a></li>
<li><a href="index.html#ohi-global" id="toc-ohi-global"><span class="toc-section-number">1.1.2</span> ohi-global</a></li>
<li><a href="index.html#ohicore" id="toc-ohicore"><span class="toc-section-number">1.1.3</span> ohicore</a></li>
<li><a href="index.html#globalfellows-issues" id="toc-globalfellows-issues"><span class="toc-section-number">1.1.4</span> globalfellows-issues</a></li>
</ul></li>
</ul></li>
<li><a href="starting-a-new-year.html#starting-a-new-year" id="toc-starting-a-new-year"><span class="toc-section-number">2</span> Starting a new year</a>
<ul>
<li><a href="starting-a-new-year.html#review-and-organize-relevant-issues" id="toc-review-and-organize-relevant-issues"><span class="toc-section-number">2.1</span> Review and organize relevant issues</a></li>
<li><a href="starting-a-new-year.html#prepare-the-repositories" id="toc-prepare-the-repositories"><span class="toc-section-number">2.2</span> Prepare the repositories!</a>
<ul>
<li><a href="starting-a-new-year.html#ohiprep-repository" id="toc-ohiprep-repository"><span class="toc-section-number">2.2.1</span> ohiprep repository</a></li>
<li><a href="starting-a-new-year.html#ohi-global-1" id="toc-ohi-global-1"><span class="toc-section-number">2.2.2</span> ohi-global</a></li>
</ul></li>
<li><a href="starting-a-new-year.html#keeping-track-of-layer-progress" id="toc-keeping-track-of-layer-progress"><span class="toc-section-number">2.3</span> Keeping track of layer progress</a></li>
</ul></li>
<li><a href="data-prep.html#data-prep" id="toc-data-prep"><span class="toc-section-number">3</span> Data Prep</a>
<ul>
<li><a href="data-prep.html#file-organization" id="toc-file-organization"><span class="toc-section-number">3.1</span> File organization</a>
<ul>
<li><a href="data-prep.html#saving-external-data" id="toc-saving-external-data"><span class="toc-section-number">3.1.1</span> Saving external data</a></li>
<li><a href="data-prep.html#vpn-setup-to-access-mazu" id="toc-vpn-setup-to-access-mazu"><span class="toc-section-number">3.1.2</span> VPN Setup to Access Mazu</a></li>
<li><a href="data-prep.html#setting-up-rstudio-mazu-server" id="toc-setting-up-rstudio-mazu-server"><span class="toc-section-number">3.1.3</span> Setting up Rstudio Mazu Server</a></li>
<li><a href="data-prep.html#using-cyberduck-or-filezilla-to-transfer-large-files" id="toc-using-cyberduck-or-filezilla-to-transfer-large-files"><span class="toc-section-number">3.1.4</span> Using Cyberduck or Filezilla to Transfer Large Files</a></li>
<li><a href="data-prep.html#globalprep-files" id="toc-globalprep-files"><span class="toc-section-number">3.1.5</span> globalprep files</a></li>
<li><a href="data-prep.html#intermediate-files-that-are-too-large-for-github" id="toc-intermediate-files-that-are-too-large-for-github"><span class="toc-section-number">3.1.6</span> Intermediate files that are too large for Github</a></li>
</ul></li>
<li><a href="data-prep.html#starting-a-new-data-prep-project" id="toc-starting-a-new-data-prep-project"><span class="toc-section-number">3.2</span> Starting a new data prep project</a>
<ul>
<li><a href="data-prep.html#prepare-the-dataprep-folder" id="toc-prepare-the-dataprep-folder"><span class="toc-section-number">3.2.1</span> Prepare the dataprep folder</a></li>
<li><a href="data-prep.html#start-an-issue" id="toc-start-an-issue"><span class="toc-section-number">3.2.2</span> Start an issue</a></li>
<li><a href="data-prep.html#update-the-files" id="toc-update-the-files"><span class="toc-section-number">3.2.3</span> Update the files</a></li>
</ul></li>
<li><a href="data-prep.html#a-typical-data-prep-script" id="toc-a-typical-data-prep-script"><span class="toc-section-number">3.3</span> A typical data prep script</a></li>
<li><a href="data-prep.html#prep-rmd-1.-summary" id="toc-prep-rmd-1.-summary"><span class="toc-section-number">3.4</span> prep Rmd: 1. Summary</a></li>
<li><a href="data-prep.html#prep-rmd-2.-updates" id="toc-prep-rmd-2.-updates"><span class="toc-section-number">3.5</span> prep Rmd: 2. Updates</a></li>
<li><a href="data-prep.html#prep-rmd-3.-data-sources" id="toc-prep-rmd-3.-data-sources"><span class="toc-section-number">3.6</span> prep Rmd: 3. Data sources</a></li>
<li><a href="data-prep.html#prep-rmd-4.-set-up" id="toc-prep-rmd-4.-set-up"><span class="toc-section-number">3.7</span> prep Rmd: 4. Set up</a>
<ul>
<li><a href="data-prep.html#packages" id="toc-packages"><span class="toc-section-number">3.7.1</span> Packages</a></li>
<li><a href="data-prep.html#common.r" id="toc-common.r"><span class="toc-section-number">3.7.2</span> common.R</a></li>
</ul></li>
<li><a href="data-prep.html#prep-rmd-5.-data-prep" id="toc-prep-rmd-5.-data-prep"><span class="toc-section-number">3.8</span> prep Rmd: 5. Data prep</a>
<ul>
<li><a href="data-prep.html#ohi-data-idiosyncracies-low-populationuninhabited-regions-and-grouped-regions" id="toc-ohi-data-idiosyncracies-low-populationuninhabited-regions-and-grouped-regions"><span class="toc-section-number">3.8.1</span> OHI data idiosyncracies: Low population/uninhabited regions and grouped regions</a></li>
</ul></li>
<li><a href="data-prep.html#prep-rmd-6.-gapfilling" id="toc-prep-rmd-6.-gapfilling"><span class="toc-section-number">3.9</span> prep Rmd: 6. Gapfilling</a>
<ul>
<li><a href="data-prep.html#training-linear-models-for-gapfilling" id="toc-training-linear-models-for-gapfilling"><span class="toc-section-number">3.9.1</span> Training linear models for gapfilling</a></li>
<li><a href="data-prep.html#saving-gapfilling-report-files" id="toc-saving-gapfilling-report-files"><span class="toc-section-number">3.9.2</span> Saving gapfilling report files</a></li>
</ul></li>
<li><a href="data-prep.html#prep-rmd-7.-results-check" id="toc-prep-rmd-7.-results-check"><span class="toc-section-number">3.10</span> prep Rmd: 7. Results check</a></li>
<li><a href="data-prep.html#prep-rmd-8.-final-run" id="toc-prep-rmd-8.-final-run"><span class="toc-section-number">3.11</span> prep Rmd: 8. Final run</a></li>
<li><a href="data-prep.html#notes-on-parallel-processing" id="toc-notes-on-parallel-processing"><span class="toc-section-number">3.12</span> Notes on parallel processing</a>
<ul>
<li><a href="data-prep.html#stopcluster-makecluster" id="toc-stopcluster-makecluster"><span class="toc-section-number">3.12.1</span> stopCluster &amp; makeCluster</a></li>
<li><a href="data-prep.html#using-htop-to-check-on-processes-running" id="toc-using-htop-to-check-on-processes-running"><span class="toc-section-number">3.12.2</span> Using htop to check on processes running</a></li>
</ul></li>
</ul></li>
<li><a href="updating-scores.html#updating-scores" id="toc-updating-scores"><span class="toc-section-number">4</span> Updating scores</a></li>
<li><a href="finalizing-the-global-assessment.html#finalizing-the-global-assessment" id="toc-finalizing-the-global-assessment"><span class="toc-section-number">5</span> Finalizing the global assessment</a>
<ul>
<li><a href="finalizing-the-global-assessment.html#create-results-folder" id="toc-create-results-folder"><span class="toc-section-number">5.1</span> Create results folder</a></li>
<li><a href="finalizing-the-global-assessment.html#final-score-review" id="toc-final-score-review"><span class="toc-section-number">5.2</span> Final score review</a></li>
<li><a href="finalizing-the-global-assessment.html#citation-management" id="toc-citation-management"><span class="toc-section-number">5.3</span> Citation management</a>
<ul>
<li><a href="finalizing-the-global-assessment.html#getting-zotero-and-rstudio-to-work-well-together" id="toc-getting-zotero-and-rstudio-to-work-well-together"><span class="toc-section-number">5.3.1</span> Getting Zotero and RStudio to work well together</a></li>
<li><a href="finalizing-the-global-assessment.html#working-with-zotero" id="toc-working-with-zotero"><span class="toc-section-number">5.3.2</span> Working with Zotero</a></li>
</ul></li>
<li><a href="finalizing-the-global-assessment.html#methods-document" id="toc-methods-document"><span class="toc-section-number">5.4</span> Methods document</a>
<ul>
<li><a href="finalizing-the-global-assessment.html#steps-to-updating-methods-document" id="toc-steps-to-updating-methods-document"><span class="toc-section-number">5.4.1</span> Steps to updating methods document</a></li>
</ul></li>
<li><a href="finalizing-the-global-assessment.html#results-document" id="toc-results-document"><span class="toc-section-number">5.5</span> Results document</a></li>
<li><a href="finalizing-the-global-assessment.html#update-esri-living-atlas-of-the-world-ohi-map" id="toc-update-esri-living-atlas-of-the-world-ohi-map"><span class="toc-section-number">5.6</span> Update ESRI Living Atlas of the World OHI map</a></li>
<li><a href="finalizing-the-global-assessment.html#github-releases" id="toc-github-releases"><span class="toc-section-number">5.7</span> Github Releases</a></li>
<li><a href="finalizing-the-global-assessment.html#upload-to-a-repository" id="toc-upload-to-a-repository"><span class="toc-section-number">5.8</span> Upload to a repository</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">OHI Global Assessment Guide</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-prep" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> Data Prep</h1>
<p>All data layers are prepared in the ohiprep_v20?? repository.</p>
<p>Spend some time researching the data prior to launching into the coding in R. I look over the files in the dataprep folder on Github, as well as the Mazu folder that contains the raw data. I research the specific data layers I will be working on and the goals/pressures/resilience dimensions they are used to calculate. I typically start in the <a href="https://raw.githack.com/OHI-Science/ohi-global/published/global_supplement/Supplement.html">methods</a> document. I also research the source data, looking over websites, reports, and published papers.</p>
<p>In regard to preparing the data, the best approach is to prepare the layer or layers within a single Rmd script and then update the OHI scores one layer at a time. This approach makes it much easier to identify and track potential errors.</p>
<p>This section will discuss:</p>
<ol style="list-style-type: decimal">
<li>File organization</li>
<li>Starting a new data prep project</li>
<li>Anatomy of a typical data prep script</li>
<li>Notes on parallel processing</li>
</ol>
<hr />
<div id="file-organization" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> File organization</h2>
<div id="saving-external-data" class="section level3" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Saving external data</h3>
<p>In almost all cases, OHI data comes from other institutions. We save these data to<br />
the NCEAS private server (Mazu) because we do not want to be responsible for distributing other people’s data.</p>
<p>These data are saved to Mazu: git-annex/globalprep/_raw_data in a folder that is labeled with an abbreviated version of the datasource (Figure 1). The data is saved to a folder describing the year the data was downloaded (e.g., d2015, d2016).</p>
<p>Figure 1: Location of raw data saved to Mazu.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vT09zXxdCewmMAuDscXvS-pAoYM92AMd8Xxw_DhP93IFirHRtioAu19IsjEUN24091Cvm7vmCkB8piM/pub?w=712&amp;h=531" /></p>
<p>Every raw data folder should have a README.md (keep the caps so it is consistent and easy to see). *Note we are using .md rather than .txt even for READMEs on Mazu.</p>
<p>Each README should include the following (<a href="https://github.com/OHI-Science/ohiprep/blob/master/src/templates/generic_raw_data_README.md">template</a>):</p>
<ul>
<li>Detailed source information. For example:
<ul>
<li>full paper citation and link for publication</li>
<li>Link to online data source</li>
<li>Full email history with data provider</li>
</ul></li>
<li>If it was downloaded online, provided written and visual instructions so that the reader can mimic your same steps to get the same data. Include screenshots if possible!</li>
<li>Version information for data</li>
<li>Years included in the datatset</li>
<li>Year the data was published</li>
<li>Type of data included in the dataset (e.g., catch per species (tons) per country)</li>
<li>Any other information that could possibly be useful to anyone</li>
</ul>
<hr />
</div>
<div id="vpn-setup-to-access-mazu" class="section level3" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> VPN Setup to Access Mazu</h3>
<p>Here is why you will want to get your VPN accounts set up:</p>
<ol style="list-style-type: decimal">
<li>You can access files on Mazu while you are offsite</li>
<li>You can run intensive memory projects on the Mazu server while you are offsite</li>
<li>You will functionally have two computers, so you can set up a long-running processes (on the Mazu server) and then you can work from your personal computer</li>
</ol>
<p>This is especially important when we start working with spatial files. It is impossible to run the spatial analyses on a personal computer due to speed and memory limitations.</p>
<p>The VPN allows you to work from the Mazu server when you are not onsite. I almost exclusively work from Mazu. Basically, when I log in, my computer thinks I am working from NCEAS. I can access the Mazu drive. My IP address is through NCEAS and my clock displays the time in Santa Barbara.</p>
<p>Here is some information on getting setup: <a href="http://www.ets.ucsb.edu/services/campus-vpn/what-vpn" class="uri">http://www.ets.ucsb.edu/services/campus-vpn/what-vpn</a>
and: <a href="http://www.ets.ucsb.edu/services/campus-vpn/get-connected" class="uri">http://www.ets.ucsb.edu/services/campus-vpn/get-connected</a></p>
<p>Once you have the VPN, here’s you can access Mazu via the Rstudio Mazu server, or via SFTP clients like Cyberduck or Filezilla (outlined below).</p>
<hr />
</div>
<div id="setting-up-rstudio-mazu-server" class="section level3" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Setting up Rstudio Mazu Server</h3>
<p>You will definitely want to get set up to run RStudio on Mazu! This is so great for so many reasons.</p>
<ol style="list-style-type: decimal">
<li>It makes it super easy to work remotely.</li>
<li>If you are running long R processes, Mazu is faster and it will not hog your computer’s resources.</li>
<li>It is possible to run scripts on Mazu’s multiple cores (which is necessary to run many of our scripts).</li>
</ol>
<p>You need to contact <a href="mailto:support@nceas.ucsb.edu" class="email">support@nceas.ucsb.edu</a> to get this set up.</p>
<p>This is what it looks like on my computer:
<img src="https://docs.google.com/drawings/d/e/2PACX-1vQMt-gUz07-sdOmHiWQn2fKGb7lOPChXwsoExZ6NiCVu0ylHv65rV3e5H6pWwic4FDas1ajjZSj4v8I/pub?w=960&amp;h=720" /></p>
<hr />
</div>
<div id="using-cyberduck-or-filezilla-to-transfer-large-files" class="section level3" number="3.1.4">
<h3><span class="header-section-number">3.1.4</span> Using Cyberduck or Filezilla to Transfer Large Files</h3>
<p>You should consider using Cyberduck or Filezilla to view and access files on the Mazu server (I prefer to use Filezilla).</p>
<p>If you need to move really big files between Mazu and your computer, I find that the using mapped VPN on your personal computer typically fails. For this, I use <a href="https://filezilla-project.org/">Filezilla</a> (Cyberduck works just fine too).</p>
<ol style="list-style-type: decimal">
<li><p>Once it is downloaded, you can open Filezilla, click the button in the top left:
<img src="images/filezilla_open.png" /></p></li>
<li><p>This will open up a new window, where you can input the server you would like to access (the same as cyberduck):
<img src="images/filezilla_window.png" /></p></li>
<li><p>I like to have it connect and open directly to OHI’s <code>git-annex</code> folder, so I don’t have to navigate there from my home folder. To do this, you can click on the “Advanced” tab in the setup, and specify the default remote directory “/home/shares/ohi/git-annex”:
<img src="images/filezilla_window_2.png" /></p></li>
<li><p>Now you should be able to see the git-annex remote directory and explore/download files/upload files, etc!
<img src="images/filezilla_explore.png" /></p></li>
</ol>
<p>Instructions for Cyberduck instead of Filezilla:</p>
<ol style="list-style-type: decimal">
<li><p>After you download Cyberduck, open it up and click Open Connection.
<img src="https://docs.google.com/drawings/d/e/2PACX-1vRkVsbyCsv3LQYuSbAueUjv2KLyiJCWL9gvJd3jCIyX-xvCHnWzWJU0gO-izhaurjdM8S5yHOCQCR_r/pub?w=960&amp;h=720" /></p></li>
<li><p>Type in the server address mazu.nceas.ucsb.edu, your sign-in credentials, select SFTP (SSH File Transfer Protocol) in the drop down at the top (supposed to be safer), AND type in /home/shares/ohi/git-annex under “Path:”. Click Connect.
<img src="https://docs.google.com/drawings/d/e/2PACX-1vSXABa8ABX-dHcOA3_--0k_y1rZCWrFuVgx2GIurOIqSRKoyZGZ7Ec0Ixt0NGlx7y6NcuB10rzfXm3A/pub?w=960&amp;h=720" /></p></li>
</ol>
<p><em>Note:</em> You can modify the path if you want to be directed to another location in mazu.</p>
<ol start="3" style="list-style-type: decimal">
<li>Now you can start dragging and dropping! Click Disconnect when you’re done using Cyberduck.</li>
</ol>
<hr />
</div>
<div id="globalprep-files" class="section level3" number="3.1.5">
<h3><span class="header-section-number">3.1.5</span> globalprep files</h3>
<p>All of the R scripts and metadata used to prepare the data, as well as the final data layers are saved in the Github ohiprep_v???? repository in the globalprep folder.</p>
<p>The only data that will not be saved on Github are files that are too large or incompatible with Github (see below).</p>
<p><strong>Primary goal/component folder</strong> The folder should be named according to the OHI target (the goal or dimension that the data is used to calculate). For example the folder for the tourism and recreation goal would be called: globalprep/tr (see table below for all folder abbreviations). These recommendations are flexible and should be modified as needed, for example goals can be combined in a single folder (e.g., spp_ico) or, there may be several folders for different components of a single goal (e.g. tr_sustainability and tr_tourists).</p>
<table>
<thead>
<tr class="header">
<th>target</th>
<th>suggested folder name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Artisanal Fishing Opportunity</td>
<td>ao</td>
</tr>
<tr class="even">
<td>Carbon Storage</td>
<td>cs</td>
</tr>
<tr class="odd">
<td>Clean Waters</td>
<td>cw</td>
</tr>
<tr class="even">
<td>Coastal Protection</td>
<td>cp</td>
</tr>
<tr class="odd">
<td>Coastal Livelihoods</td>
<td>liv</td>
</tr>
<tr class="even">
<td>Coastal Economies</td>
<td>eco</td>
</tr>
<tr class="odd">
<td>Fisheries</td>
<td>fis</td>
</tr>
<tr class="even">
<td>Habitats</td>
<td>hab</td>
</tr>
<tr class="odd">
<td>Iconic Species</td>
<td>ico</td>
</tr>
<tr class="even">
<td>Lasting Special Places</td>
<td>lsp</td>
</tr>
<tr class="odd">
<td>Mariculture</td>
<td>mar</td>
</tr>
<tr class="even">
<td>Natural Products</td>
<td>np</td>
</tr>
<tr class="odd">
<td>Species</td>
<td>spp</td>
</tr>
<tr class="even">
<td>Tourism and Recreation</td>
<td>tr</td>
</tr>
<tr class="odd">
<td>Pressure</td>
<td>prs_<em>additional_pressure_id</em></td>
</tr>
<tr class="even">
<td>Resilience</td>
<td>res_<em>additional_resilience_id</em></td>
</tr>
</tbody>
</table>
<p>This folder will contain:</p>
<ul>
<li><p>a <em>README.md</em> that will link to the appropriate information pages on ohi-science.org The README.md should follow this <a href="https://github.com/OHI-Science/ohiprep/blob/master/src/templates/generic_readme.md">template</a>.</p></li>
<li><p><strong>Year-specific folders</strong> within the goal/component folder organize output by assessment year (v2015, v2016). Each of the assessment year folders should have:
* a README.md (see <a href="https://github.com/OHI-Science/ohiprep/blob/master/src/templates/generic_readme_year.md">this template</a>)
* a data_prep.R, or .Rmd that is well-documented. <a href="https://github.com/OHI-Science/ohiprep/blob/master/src/templates/generic_data_prep.Rmd">Here is the dataprep template</a>.
* a series of folders to organize data that include:
+ <code>raw</code> for ‘raw-ish’ type files that would not be on the server. This is typically for piecemeal raw data that we compile (e.g., U.S. State Department travel warnings), and not data we have downloaded from a single source (which would go on Mazu). In most cases, this folder will not be used.
+ <code>int</code> for intermediate files (previously we’ve used tmp, working, or other naming conventions so this might not be entirely consistent).
+ <code>output</code> for the final data layer that is used in the OHI toolbox.</p></li>
</ul>
<p>The final datasets (the ones stored in the <code>output</code> folder) will be preceeded by the target abbreviation followed by an underscore that provides a brief description of the data, e.g., tr_sustainability.csv).</p>
<!--- TODO Slightly confused as to what this image is supposed to be showing us. Is this showing corrections that should be made to mistakes? --->
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vQL9FTF2lZ3yBCv9ZEI7OQ0sNCGdKpUrP0FfjtV_14vvzHAx3rxMQLJ-nFcfjRVT61sHTti4Husmrm-/pub?w=960&amp;h=720" /></p>
<hr />
</div>
<div id="intermediate-files-that-are-too-large-for-github" class="section level3" number="3.1.6">
<h3><span class="header-section-number">3.1.6</span> Intermediate files that are too large for Github</h3>
<p>These files will be saved on Mazu, the internal server’s, globalprep folder.</p>
<p>Our goal is to have everything (except for data obtained from other sources) stored on GitHub, but some files are too large or inappropriate for GitHub and must be stored on Mazu. Each of these files should be stored in a way that mirrors that on Github. If there is a need to make a duplicate folder on <code>git-annex</code>, it should have the same name as the folder used in GitHub.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vQjq4gTVyHmB-QKIAAWEin3YRPSsEqoq2yZZ0W5uP6D47vXAZUoNJl21BPKLumifz_UgbZ_ef1-U0lt/pub?w=960&amp;h=720" /></p>
<p>Store any intermediate or final output files that are too large for github in these folders. Keep the same subfolder structure. If you are working in <code>spp_ico</code> and have temporary rasters to store on Mazu, save them in a folder named <code>int</code>.</p>
<p><strong>Raw data should not be stored here. This should be stored in Mazu’s <code>_raw_data</code> folder</strong></p>
<hr />
</div>
</div>
<div id="starting-a-new-data-prep-project" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Starting a new data prep project</h2>
<div id="prepare-the-dataprep-folder" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Prepare the dataprep folder</h3>
<p>In ohiprep_v20??/globalprep navigate to the folder that contains the files you will need to prepare the data. Select the most recent assessment year of data and copy/paste to create a new folder in the same location, changing the name to reflect the current assessment year.</p>
<p>For example, if we are preparing data layers for the 2019 assessment for the artisanal opportunities goal, ao, we would copy the v2018 folder and name it v2019.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vTkXdx-bGQoOhzXn6Wz94yV9_S9BlKY0kPhAtp9nKaewr0lRD0Cr0B_H37aUoDANt0Ck6p4wSaFIJPz/pub?w=960&amp;h=720" />
Next, delete all unnecessary files, particularly the files in the raw, intermediate, and output folders! New versions of these data will be created in the updated data_prep script, and you want to be sure that this is indeed what happens. If there are data already in the folder it can be easy to overlook a mistake, such as not using the correct file path to save the data, etc..</p>
<p>Typically, you will not delete the dataprep script/s and README. You will also want to preserve the folder structure. If in doubt, I delete the files and then copy them over as needed. For some goals, such as fisheries, there are lots and lots of files and it is very confusing. In these cases, I just copy the files as I need them.</p>
<p>Once you have created and cleaned the new folder commit and push the updates!</p>
</div>
<div id="start-an-issue" class="section level3" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Start an issue</h3>
<p>On Github create an issue for this dataprep project. Here you will document progress, report problems or concerns, pose questions, describe changes to code, and report on final results. For example, if working on the artisanal opportunities dataprep, name the issue “Artisanal opportunities”.</p>
<p>Once the relevant data layers are created and incorporated into the OHI scores this issue will be closed.</p>
</div>
<div id="update-the-files" class="section level3" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Update the files</h3>
<p>Carefully walk through the data prep scripts and update as necessary.</p>
<p>You will also need to update READMEs.</p>
<p>As you check and update the scripts, don’t assume everything is correct. There could be changes to the source data that introduce errors (this often happens). We could have made a mistake somewhere. And, even if there aren’t any mistakes, there is usually room for improvement.</p>
<p>Checking the dataprep scripts involves:</p>
<ul>
<li>Going through each line of code to understand what is happening. Each step of dplyr chains should be evaluated, rather than running the entire chain and assuming it is correct.</li>
<li>Using functions such as summary, dim, length functions and figures to explore the data at different stages of preparation.</li>
<li>Check the dimensions of the dataframe after each join or spread/collapse to ensure the length of the updated data makes sense.</li>
<li>Check that the frequency of NA values seems reasonable, especially after joins and spread/collapse functions. And, if you gapfill missing values, make sure that you end up estimating all NA values. Note: for some layers, uninhabited/low-population regions will be manually assigned NA values.</li>
</ul>
<hr />
</div>
</div>
<div id="a-typical-data-prep-script" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> A typical data prep script</h2>
<p>All data prep is performed in R or, preferrably, R Markdown (Rmd) documents. Rmd is an ideal format because it seemlessly integrates code and documentation, can display figures, and the output provides a clean methods document.</p>
<p>We have several shared practices for preparing data:</p>
<ul>
<li>Ideally Rmd/R files are used to download and save source datafiles, but this isn’t possible in most cases due to the format of the data.</li>
<li>We put a large premium on documenting the steps used to prepare data!</li>
<li>In many cases, the data preparation for a goal is performed in a single file. But, for more complex goals it is better to break the data preparation into multiple Rmd documents. If multiple Rmd documents are used, a README must describe what each Rmd document does, the input/outputs, and the order of processing.<br />
</li>
<li>If a process is run multiple times, the code should be converted to a function and placed in folder labeled R or worklflow.</li>
<li>The <code>here</code> package, and <code>here()</code> function should be used control relative file paths.</li>
<li>We use the tidyverse for tidying data</li>
</ul>
<p>A typical data prep script (or series of scripts) will include the following sections, which are described in more detail below:</p>
<ol style="list-style-type: decimal">
<li>Summary: general description of the data prepared by the script</li>
<li>Updates: updates to source data and/or methods from previous year</li>
<li>Data sources: description of source data</li>
<li>Set up: code chunk that loads relevant R packages and functions</li>
<li>Data prep: code chunks for preparing the data, this is typically the bulk of the Rmd file</li>
<li>Gapfilling: code chunks for estimating and documenting missing data</li>
<li>Results check: code used to check results</li>
<li>Final run: a final run of all the code after restarting R</li>
</ol>
<p>A generic data prep Rmd file is located on Github: <a href="https://raw.githubusercontent.com/OHI-Science/ohiprep/master/src/templates/generic_data_prep.Rmd">https://raw.githubusercontent.com/OHI-Science/ohiprep/master/src/templates/generic_data_prep.Rmd</a></p>
</div>
<div id="prep-rmd-1.-summary" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> prep Rmd: 1. Summary</h2>
<p>This section describes the purpose of the script and the data layers that are generated.</p>
<p>For example, the 2019 AO summary looks like this:</p>
<ul>
<li>“This script generates the”need” layer for the artisanal opportunities goal. The “access” layer, which is not updated due to a lack of a data source, is located here: globalprep/res_mora_ao/v2013/data/r_mora_s4_2013a.csv.”</li>
</ul>
</div>
<div id="prep-rmd-2.-updates" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> prep Rmd: 2. Updates</h2>
<p>This section describes all the updates to source data and/or methods since the previous year’s assessment.</p>
<p>For example, the 2019 AO updates look like this:</p>
<ul>
<li>“Uninhabited and low population regions now given an NA value (vs. a gapfilled value).”</li>
<li>“Added an additional year of GDP data from the World Bank”</li>
</ul>
</div>
<div id="prep-rmd-3.-data-sources" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> prep Rmd: 3. Data sources</h2>
<p>This section describes all data sources and may include:</p>
<p><strong>Reference</strong>: [citation for source data; website, literature, contact information. Version of data (if relevant).]</p>
<p><strong>Downloaded</strong>: [date downloaded or received]</p>
<p><strong>Description</strong>: [e.g., surface aragonite state]</p>
<p><strong>Native data resolution</strong>: [e.g., 1 degree, 30 m, country, etc.]</p>
<p><strong>Time range</strong>: [e.g., 1880-1899, monthly data provided for each year]</p>
<p><strong>Format</strong>: [e.g., NetCDF, Excel file]
<br> <br></p>
<p>For example, the 2018 AO data sources section looks like this:</p>
<p><strong>Downloaded</strong>: 7/23/2018</p>
<p><strong>Description</strong>:<br />
GDP adjusted per capita by PPP (ppppcgdp)
<a href="http://data.worldbank.org/indicator/NY.GDP.PCAP.PP.KD" class="uri">http://data.worldbank.org/indicator/NY.GDP.PCAP.PP.KD</a>
Reported at country scale.</p>
<p>GDP per capita based on purchasing power parity (PPP). PPP GDP is gross domestic product converted to international dollars using purchasing power parity rates. An international dollar has the same purchasing power over GDP as the U.S. dollar has in the United States. GDP at purchaser’s prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in constant international dollars based on the 2011 ICP round.</p>
<p>Data is available directly to R through the WDI package.</p>
<p><strong>Time range</strong>: 1990-2017</p>
</div>
<div id="prep-rmd-4.-set-up" class="section level2" number="3.7">
<h2><span class="header-section-number">3.7</span> prep Rmd: 4. Set up</h2>
<p>This code chunk is used to load packages, source functions, and set variables used throughout the analyses.</p>
<p>Here, you can also initialize programatic creation of raw, intermediate and output file folders within the specific layer directory:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="data-prep.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check if &#39;raw&#39;, &#39;intermediate&#39;, and &#39;final&#39; folders exist in the current assessment folder, if not, then create the folder in the working directory</span></span>
<span id="cb1-2"><a href="data-prep.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(<span class="fu">here</span>(<span class="st">&quot;globalprep/layer_name/v20??/raw&quot;</span>))){</span>
<span id="cb1-3"><a href="data-prep.html#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">&quot;globalprep/layer_name/v20??/raw&quot;</span>))</span>
<span id="cb1-4"><a href="data-prep.html#cb1-4" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb1-5"><a href="data-prep.html#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="data-prep.html#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(<span class="fu">here</span>(<span class="st">&quot;globalprep/layer_name/v20??/intermediate&quot;</span>))){</span>
<span id="cb1-7"><a href="data-prep.html#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">&quot;globalprep/layer_name/v20??/intermediate&quot;</span>))</span>
<span id="cb1-8"><a href="data-prep.html#cb1-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-9"><a href="data-prep.html#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="data-prep.html#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(<span class="fu">here</span>(<span class="st">&quot;globalprep/layer_name/v20??/output&quot;</span>))){</span>
<span id="cb1-11"><a href="data-prep.html#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">&quot;globalprep/layer_name/v20??/output&quot;</span>))</span>
<span id="cb1-12"><a href="data-prep.html#cb1-12" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div id="packages" class="section level3" number="3.7.1">
<h3><span class="header-section-number">3.7.1</span> Packages</h3>
<p>The packages we load depend on the analyses, but we always use:</p>
<ul>
<li>dplyr and tidyr: data wrangling tools <a href="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">a cheatsheet</a></li>
</ul>
<div id="packages-commonly-include-but-are-not-limited-to" class="section level4" number="3.7.1.1">
<h4><span class="header-section-number">3.7.1.1</span> Packages commonly include, but are not limited to:</h4>
<p><strong>OHIcore package which contains all the proprietary OHI functions</strong></p>
<ul>
<li>library(ohicore)</li>
<li>Check to see if it is installed and install it if not: <code>if (!("ohicore" %in% installed.packages())){devtools::install_github("ohi-science/ohicore")}</code></li>
</ul>
<p><strong>General data analysis and wrangling packages:</strong></p>
<ul>
<li><code>library(here)</code> - controls file paths, learn more <a href="https://github.com/jennybc/here_here">here</a></li>
<li><code>library(tidyverse)</code> - includes ggplot2, readr, stringr, tidyr, and dplyr</li>
<li><code>library(plotly)</code> - create interactive ggplots</li>
<li><code>library(zoo)</code> - usually used for time series data</li>
</ul>
<p><strong>Packages used for spatial analysis:</strong></p>
<ul>
<li><code>library(raster)</code> - reading, writing, manipulating, analyzing and modeling of gridded spatial data</li>
<li><code>library(fasterize)</code> - a better way to convert a shapefile to a raster file</li>
<li><code>library(sf)</code> - a new version of sp, providing a standardized way to encode spatial vector data</li>
<li><code>library(sp)</code> - classes and methods for spatial data</li>
<li><code>library(rgdal)</code> - tools for dealing with coordinate reference systems</li>
</ul>
<p><strong>Parallel processing libraries (usually used for data prep involving large spatial files):</strong></p>
<ul>
<li><code>library(parallel)</code></li>
<li><code>library(foreach)</code></li>
<li><code>library(doParallel)</code></li>
</ul>
</div>
</div>
<div id="common.r" class="section level3" number="3.7.2">
<h3><span class="header-section-number">3.7.2</span> common.R</h3>
<p>Nearly all scripts will source a common.R file. This file creates several objects that make it easier to conduct an OHI assessment. This includes:</p>
<table>
<colgroup>
<col width="21%" />
<col width="78%" />
</colgroup>
<thead>
<tr class="header">
<th>object</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>dir_M</td>
<td>file path to Mazu</td>
</tr>
<tr class="even">
<td>mollCRS</td>
<td>crs code for the mollweide coordinate refernce system we use in the global assessment</td>
</tr>
<tr class="odd">
<td>regions_shape()</td>
<td>A function to load a simple feature object called “regions” with polygons for land/eez/highseas/antarctica regions. The “regions” object uses the Mollweide coordinate reference system.</td>
</tr>
<tr class="even">
<td>ohi_rasters()</td>
<td>function to load two rasters: global eez regions and ocean region</td>
</tr>
<tr class="odd">
<td>rgn_data()</td>
<td>function to load 2 dataframes describing global regions</td>
</tr>
<tr class="even">
<td>rgn_syns()</td>
<td>function to load dataframe of region synonyms (used to convert country names to OHI regions)</td>
</tr>
<tr class="odd">
<td>low_pop()</td>
<td>function to load dataframe of regions with low and no human population</td>
</tr>
<tr class="even">
<td>UNgeorgn()</td>
<td>function to load dataframe of UN sociopolitical regions, typically used to gapfill missing data</td>
</tr>
</tbody>
</table>
<p>To load the data in a data function:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="data-prep.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;http://ohi-science.org/ohiprep_v2019/workflow/R/common.R&#39;</span>)</span></code></pre></div>
<pre><code>## This file makes it easier to process data for the OHI global assessment
##  by creating the following objects:
## 
##  * dir_M = identifies correct file path to Mazu (internal server) based on your operating system
##  * mollCRS = the crs code for the mollweide coordinate reference system we use in the global assessment
##  * regions_shape() = function to load global shapefile for land/eez/high seas/antarctica regions
##  * ohi_rasters() = function to load two rasters: global eez regions and ocean region
##  * region_data() = function to load 2 dataframes describing global regions 
##  * rgn_syns() = function to load dataframe of region synonyms (used to convert country names to OHI regions)
##  * low_pop() = function to load dataframe of regions with low and no human population
##  * UNgeorgn = function to load dataframe of UN geopolitical designations used to gapfill missing data</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="data-prep.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call the function to load the data, the message describes the available data: </span></span>
<span id="cb4-2"><a href="data-prep.html#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">region_data</span>()</span></code></pre></div>
<pre><code>## loads 2 dataframes: rgns_all and rgns_eez 
##  rgns_all = includes eez/high seas/antarctica regions, IDs correspond with region shapefile and raster
##  rgns_eez = includes only eez regions</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="data-prep.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rgns_all)</span></code></pre></div>
<pre><code>##   rgn_type type_w_ant rgn_id rgn_ant_id              rgn_name
## 1      eez        eez      1          1         Cocos Islands
## 2      eez        eez     10         10                 Nauru
## 3      eez        eez    100        100   Republique du Congo
## 4      eez        eez    101        101               Namibia
## 5      eez        eez    102        102          South Africa
## 6      eez        eez    103        103 Sao Tome and Principe</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="data-prep.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rgns_eez)</span></code></pre></div>
<pre><code>##   rgn_id         rgn_name eez_iso3 territory admin_rgn_id admin_country_name
## 1      1    Cocos Islands      CCK       yes           16          Australia
## 2      2 Christmas Island      CXR       yes           16          Australia
## 3      3   Norfolk Island      NFK       yes           16          Australia
## 4      4 Macquarie Island      AUS       yes           16          Australia
## 5      5    New Caledonia      NCL       yes          179             France
## 6      6          Vanuatu      VUT        no            6            Vanuatu
##   Notes
## 1      
## 2      
## 3      
## 4      
## 5      
## 6</code></pre>
<div id="metadata-for-common.r" class="section level4" number="3.7.2.1">
<h4><span class="header-section-number">3.7.2.1</span> metadata for common.R</h4>
<p><strong>dir_M and mollCRS</strong></p>
<p>The following are the dir_M and mollCRS objects:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="data-prep.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## dir_M describes the path to our internal server based on your computer&#39;s operating system</span></span>
<span id="cb10-2"><a href="data-prep.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="do">## </span><span class="al">NOTE</span><span class="do">: The following may be different on your operating system</span></span>
<span id="cb10-3"><a href="data-prep.html#cb10-3" aria-hidden="true" tabindex="-1"></a>dir_M</span></code></pre></div>
<pre><code>## [1] &quot;/home/shares/ohi&quot;</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="data-prep.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">## mollCRS is the code for the Mollweide coordinate reference system</span></span>
<span id="cb12-2"><a href="data-prep.html#cb12-2" aria-hidden="true" tabindex="-1"></a>mollCRS</span></code></pre></div>
<pre><code>## Coordinate Reference System:
## Deprecated Proj.4 representation:
##  +proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs</code></pre>
<p><strong>regions_shape</strong></p>
<p>The regions_shape function returns a simple feature object called “regions”. Regions is the master global shapefile that includes polygons for land, eez, high seas, and antarctica regions in the Mollweide coordinate reference system.</p>
<p>Sometimes it is necessary to convert from a simple feature object to a shapefile object because some functions still do not work with simple feature objects, or, if the spatial file is modified, a saved shapefile may be desired. This is accomplished like this:</p>
<p><code>regions_shape &lt;- as(regions, "Spatial")</code></p>
<!--- TODO Can't get any of these code chunks to run. Are they necessary to run? Need to discuss with Mel--->
<p>The regions file with eez (dark blue), fao or high seas (light blue), and antarctica or CCAMLR (green) regions.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vRpNcorAKw0Hzk--d1R_llBw4-qeCx1mcgDSpaUeIASO2YDBIhPcoEXMshIFHgo9nv8E6_o6h70fs-P/pub?w=960&amp;h=720" /></p>
<p>The regions object is a simple feature multipolygon spatial object in the Mollweide coordinate reference system. There are 7 fields described in the table</p>
<table>
<colgroup>
<col width="13%" />
<col width="23%" />
<col width="22%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>data type</th>
<th>description</th>
<th>examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>type_w_ant</td>
<td>factor</td>
<td>identifies all polygons as eez, fao (high seas), ccamlr (antarctica), or land</td>
<td>eez (n=220), fao (15), eez-ccamlr (19), land (220), land-ccamlr (9), eez-disputed (1), land-disputed (1), eez-inland (3), land-noeez (38)</td>
</tr>
<tr class="even">
<td>rgn_type</td>
<td>factor</td>
<td>similar to type_w_ant, but does not specify eez/ccamlr and land/land-ccamlr regions</td>
<td>eez (n=239), fao (15), land (229), eez-disputed (1), land-disputed (1), eez-inland (3), land-noeez (38)</td>
</tr>
<tr class="odd">
<td>rgn_ant_id</td>
<td>numeric</td>
<td>region ids</td>
<td>1-250 country land and eez (these are the official global regions; some numbers are skipped); 255 disputed land and eez; 260-277 fao high seas; 301-337 (country land, no eez); 248100-288300 CCAMLR regions</td>
</tr>
<tr class="even">
<td>rgn_id</td>
<td>numeric</td>
<td>region ids; similar to rgn_ant_id, but Antartica/CCAMLR regions lumped as region 213</td>
<td>1-250 country land and eez (these are the official global regions; some numbers are skipped); 255 disputed land and eez; 260-277 fao high seas; 301-337 (country land, no eez)</td>
</tr>
<tr class="odd">
<td>rgn_name</td>
<td>character</td>
<td>country/territory name</td>
<td>e.g., Afghanistan, Belize, Prince Edward Islands</td>
</tr>
<tr class="even">
<td>rgn_key</td>
<td>factor</td>
<td>3 letter identification code</td>
<td>e.g., AFG, BEL</td>
</tr>
<tr class="odd">
<td>area_km2</td>
<td>numeric</td>
<td>area of region, km2</td>
<td>range of 1-30604795</td>
</tr>
</tbody>
</table>
<p><strong>ohi_rasters</strong></p>
<p>The ohi_rasters function returns two rasters, “zones” and “ocean”, both with ~1 km resolution and the mollweide coordinate reference system.</p>
<p>The “zones” raster cell values are the OHI region ID. The raster cell values can be linked to the region names using the region_data() function, and the rgn_ant_id variable from rgns_all.csv. This raster is typically used to extract pressure data for the eez regions.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vQ7vOBar-Xr6QH8X36WsJidS0M_L4hhTQh6wgT4RTvIVJAgR04fWEqOP3oAbUcdg4JgWOu8sgzHhw0E/pub?w=960&amp;h=720" /></p>
<p>The “ocean” raster identifies ocean cells with a value of 1, and other cells are NA [NOTE: There is something weird about this raster in that it lists the values as 0, 255 (min, max), when in fact there are only 1 and NA values! If you need to convince yourself of this, you can use the <code>freq(ocean)</code> function to identify all cell values.]. This raster file is typically used to mask the ocean regions for pressure data.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vTyex8lM_fxw6-23Z1mY59Ejf3PkcBUYOYtgVx7aqjNAqtPwEmIgG289EcY9B3wLlgvrp9tTA2iCRbO/pub?w=960&amp;h=720" /></p>
<p><strong>region_data()</strong></p>
<p>The region_data function returns two dataframes, “rgns_all” and “rgns_eez”.</p>
<p>The “rgns_all” dataframe includes data for the eez, fao, and ccamlr ocean regions. The IDs in rgn_ant_id correspond to the IDs in the zones raster. Once raster data are extracted for each region, the output is often aligned with the data in this dataframe.</p>
<p><strong>Metadata for rgns_all dataframe</strong></p>
<table>
<colgroup>
<col width="13%" />
<col width="23%" />
<col width="22%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>data type</th>
<th>description</th>
<th>examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rgn_type</td>
<td>factor</td>
<td>similar to type_w_ant, but does not specify eez/ccamlr and types</td>
<td>eez (n=239), fao (15)</td>
</tr>
<tr class="even">
<td>type_w_ant</td>
<td>factor</td>
<td>identifies all ocean polygons as eez, fao (high seas), ccamlr (antarctica)</td>
<td>eez (n=220), fao (15), eez-ccamlr (19)</td>
</tr>
<tr class="odd">
<td>rgn_id</td>
<td>numeric</td>
<td>region ids; similar to rgn_ant_id, but Antartica/CCAMLR regions lumped as region 213</td>
<td>1-250 country eez (these are the official global regions; some numbers are skipped); 255 disputed eez; 260-277 fao high seas</td>
</tr>
<tr class="even">
<td>rgn_ant_id</td>
<td>numeric</td>
<td>region ids</td>
<td>1-250 country eez (these are the official global regions; some numbers are skipped); 255 disputed eez; 260-277 fao high seas; 248100-288300 CCAMLR regions</td>
</tr>
<tr class="odd">
<td>rgn_name</td>
<td>character</td>
<td>country/territory name</td>
<td>e.g., Afghanistan, Belize, Prince Edward Islands</td>
</tr>
</tbody>
</table>
<p>The “rgns_eez” dataframe includes data for the 220 OHI regions plus Antarctica (rgn_id 213). This file is used to make sure that all regions are included in dataprep files. It also includes data to indicate whether regions are territories. This can also be used for gapfilling (in some cases, it makes sense to assign territories the same value as their administrative country).</p>
<p><strong>Metadata for rgns_eez dataframe</strong></p>
<table>
<colgroup>
<col width="13%" />
<col width="22%" />
<col width="22%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>data type</th>
<th>description</th>
<th>examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rgn_id</td>
<td>numeric</td>
<td>official global regions (except Antarctica, 213)</td>
<td>1-250</td>
</tr>
<tr class="even">
<td>rgn_name</td>
<td>character</td>
<td>country/territory name</td>
<td>e.g., Afghanistan, Belize, Prince Edward Islands</td>
</tr>
<tr class="odd">
<td>eez_iso3</td>
<td>factor</td>
<td>3 letter identification code</td>
<td>e.g., AFG, BEL</td>
</tr>
<tr class="even">
<td>territory</td>
<td>boolean</td>
<td>identifies whether the region is a territory</td>
<td>yes/no</td>
</tr>
<tr class="odd">
<td>admin_rgn_id</td>
<td>numeric</td>
<td>administrative country rgn_id if a territory, otherwise the rgn_id</td>
<td>1-250</td>
</tr>
<tr class="even">
<td>admin_country_name</td>
<td>character</td>
<td>administrative country name if a territory, otherwise the country name</td>
<td>e.g., Afghanistan, Belize, Canada</td>
</tr>
</tbody>
</table>
<p><strong>region_syns()</strong></p>
<p>Observed synonyms for each region, such that each region may have multiple synonyms. These data are used to convert outside data to the OHI region name and ID. This list is updated nearly everytime we run an assessment!</p>
<p><strong>Metadata for region_syns dataframe</strong></p>
<table>
<colgroup>
<col width="13%" />
<col width="23%" />
<col width="22%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>data type</th>
<th>description</th>
<th>examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rgn_id</td>
<td>numeric</td>
<td>region ids</td>
<td>1-250</td>
</tr>
<tr class="even">
<td>rgn_name</td>
<td>character</td>
<td>country/territory name</td>
<td>e.g., Federated State of Micronesia; Micronesia, FS; Micronesia (Federated States of)</td>
</tr>
<tr class="odd">
<td>rgn_key</td>
<td>factor</td>
<td>2-letter code for countries</td>
<td>e.g., FM</td>
</tr>
<tr class="even">
<td>eez_iso3</td>
<td>factor</td>
<td>3-letter code for countries</td>
<td>e.g., FSM</td>
</tr>
<tr class="odd">
<td>rgn_typ</td>
<td>factor</td>
<td>status of region</td>
<td>disputed, landlocked, largescale (global, world); ohi_region</td>
</tr>
</tbody>
</table>
<p><strong>low_pop()</strong></p>
<p>Includes data for 21 regions with 0 and low populations. These data are used to identify regions that should have NA values because the goal does not apply to regions with no/low populations (e.g., livelihoods and economies).</p>
<p><strong>Metadata for low_pop dataframe</strong></p>
<table>
<colgroup>
<col width="13%" />
<col width="22%" />
<col width="22%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>data type</th>
<th>description</th>
<th>examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rgn_id</td>
<td>numeric</td>
<td>region ids</td>
<td>1-250</td>
</tr>
<tr class="even">
<td>rgn_nam</td>
<td>character</td>
<td>country/territory name</td>
<td>e.g., Macquarie Island, Wake Island</td>
</tr>
<tr class="odd">
<td>Southern_Island</td>
<td>boolean</td>
<td>indicates if region is a southern island</td>
<td>1/0</td>
</tr>
<tr class="even">
<td>Inhabited</td>
<td>boolean</td>
<td>indicates if region is uninhabited</td>
<td>boolean, 1/0</td>
</tr>
<tr class="odd">
<td>est_population</td>
<td>numeric</td>
<td>number of established people in region</td>
<td>0-3000</td>
</tr>
</tbody>
</table>
<p><strong>UNgeorgn()</strong></p>
<p>Each global regions UN georegion based on social and geopolitical considerations.</p>
<p><strong>Metadata for UNgeorgn dataframe</strong></p>
<table>
<colgroup>
<col width="13%" />
<col width="22%" />
<col width="22%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>data type</th>
<th>description</th>
<th>examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rgn_id</td>
<td>numeric</td>
<td>region ids</td>
<td>1-250</td>
</tr>
<tr class="even">
<td>r0_label</td>
<td>factor</td>
<td>most inclusive category</td>
<td>World</td>
</tr>
<tr class="odd">
<td>r1_label</td>
<td>factor</td>
<td>7 classes</td>
<td>Africa (N=46), Americas (3), Asia (39), Europe (43), Latin America and the Caribbean (48), Oceana (34) Southern Islands (7)</td>
</tr>
<tr class="even">
<td>r2_label</td>
<td>factor</td>
<td>22 classes</td>
<td>e.g., New Zealand, Melanesia</td>
</tr>
<tr class="odd">
<td>rgn_label</td>
<td>character</td>
<td>global region name</td>
<td>e.g., Cocos Islands, Christmas Island</td>
</tr>
<tr class="even">
<td>Inhabited</td>
<td>boolean</td>
<td>indicates if region is uninhabited</td>
<td>boolean, 1/0</td>
</tr>
<tr class="odd">
<td>est_population</td>
<td>numeric</td>
<td>number of established people in region</td>
<td>0-3000</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="prep-rmd-5.-data-prep" class="section level2" number="3.8">
<h2><span class="header-section-number">3.8</span> prep Rmd: 5. Data prep</h2>
<p>We follow several coding practices when preparing our data:</p>
<ul>
<li><p>Code chunks are broken into manageable pieces and are proceeded by a description of what is being accomplished</p></li>
<li><p>The code within a chunk is documented to make it easier to follow and to help prevent errors. For example, expected values and results are described to help prevent potential errors (e.g., check to see all values between 0-1, length should be 0, etc.).</p></li>
<li><p>Run-on dplyr chains are avoided because they are impossible to follow and prone to error!</p></li>
<li><p>Data is checked throughout the dataprep process (checking dimensions of data after joins, special attention to missing data, etc.)</p></li>
<li><p>Intermediate data files are saved if they computationally take a long time to create or have information that could be useful in other aspects of the analysis.</p></li>
<li><p>The here package is used to standardize file paths.</p></li>
</ul>
<p>The final output should be a dataframe that includes:</p>
<ul>
<li><em>rgn_id</em> All 220 regions should be included in the final file!</li>
<li><em>year</em> This should include all years of data necessary to calculate scores for all scenario years, including trend. For some data layers the data has never been updated, in these cases, there is still a year column but it may only contain a single year.</li>
<li><em>value</em> This column will contain the calculated value for the data, and the column name will vary across datasets. In general, naming conventions should be consistently used every year, but feel free to modify the column name if you feel it could be improved. Just be sure to make the corresponding change to the “name_data_fld” in this file: <a href="https://github.com/OHI-Science/ohi-global/blob/draft/metadata_documentation/layers_eez_base.csv" class="uri">https://github.com/OHI-Science/ohi-global/blob/draft/metadata_documentation/layers_eez_base.csv</a>.</li>
</ul>
<p>This file should be saved as a .csv file in an “output” folder. In general, the name of the file should be the same as the previous year. However, if you feel the file name can be improved, you will need to update the fn variable in this data file:</p>
<p><a href="https://github.com/OHI-Science/ohi-global/blob/draft/metadata_documentation/layers_eez_base.csv" class="uri">https://github.com/OHI-Science/ohi-global/blob/draft/metadata_documentation/layers_eez_base.csv</a></p>
<div id="ohi-data-idiosyncracies-low-populationuninhabited-regions-and-grouped-regions" class="section level3" number="3.8.1">
<h3><span class="header-section-number">3.8.1</span> OHI data idiosyncracies: Low population/uninhabited regions and grouped regions</h3>
<p>Recently we have standardized how we identify low population regions, using the low_pop() function in the common.R file. These regions are assigned NAs for some goals (e.g. GDP values used in AO) and perfect scores for others (e.g. sanitation access). Use the following code to establish a vector of low pop regions that can be compared against the final dataset.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="data-prep.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># After sourcing common.R and gapfilling data: </span></span>
<span id="cb14-2"><a href="data-prep.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">low_pop</span>()</span>
<span id="cb14-3"><a href="data-prep.html#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="data-prep.html#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out regions that have populations &gt; 3000 and keep NA values </span></span>
<span id="cb14-5"><a href="data-prep.html#cb14-5" aria-hidden="true" tabindex="-1"></a>low_pop <span class="ot">&lt;-</span> low_pop <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="data-prep.html#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(est_population <span class="sc">&lt;</span> <span class="dv">3000</span> <span class="sc">|</span> <span class="fu">is.na</span>(est_population)) </span>
<span id="cb14-7"><a href="data-prep.html#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="data-prep.html#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a vector of low population region IDs:</span></span>
<span id="cb14-9"><a href="data-prep.html#cb14-9" aria-hidden="true" tabindex="-1"></a>low_pop_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(low_pop<span class="sc">$</span>rgn_id)  </span>
<span id="cb14-10"><a href="data-prep.html#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="data-prep.html#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign NA values in score column for low popuation areas:</span></span>
<span id="cb14-12"><a href="data-prep.html#cb14-12" aria-hidden="true" tabindex="-1"></a>gapfilled_dataset<span class="sc">$</span>score[gapfilled_dataset<span class="sc">$</span>rgn_id <span class="sc">%in%</span> low_pop_vector] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<p>Several of the datasets we use also report OHI regions as a group, and we want to report them all at the same scale/resolution used in OHI. For instance, Bonaire, Sint Eustatius and Saba are often reported together as “Caribbean Netherlands” or combined as “Bonaire, Sint Eustatius and Saba”. Use the following code to apply the data to all three regions:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="data-prep.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming &quot;tidy_dataset&quot; has been wrangled, cleaned, and has column &quot;country&quot;</span></span>
<span id="cb15-2"><a href="data-prep.html#cb15-2" aria-hidden="true" tabindex="-1"></a>CN <span class="ot">&lt;-</span> <span class="fu">filter</span>(tidy_dataset, country<span class="sc">==</span><span class="st">&quot;Caribbean Netherlands&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="data-prep.html#cb15-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">rename</span>(<span class="at">country_old =</span> country) <span class="co"># country could also be rgn_name </span></span>
<span id="cb15-4"><a href="data-prep.html#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="data-prep.html#cb15-5" aria-hidden="true" tabindex="-1"></a>CN_subregions <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">country_old =</span> <span class="st">&quot;Caribbean Netherlands&quot;</span>,</span>
<span id="cb15-6"><a href="data-prep.html#cb15-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">country =</span> <span class="fu">c</span>(<span class="st">&quot;Bonaire&quot;</span>, <span class="st">&quot;Sint Eustatius&quot;</span>, <span class="st">&quot;Saba&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="data-prep.html#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(CN) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="data-prep.html#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>country_old)</span>
<span id="cb15-9"><a href="data-prep.html#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="data-prep.html#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove lines of data for Caribbean Netherlands and replace with individual region-level data for the three subregions:</span></span>
<span id="cb15-11"><a href="data-prep.html#cb15-11" aria-hidden="true" tabindex="-1"></a>tidy_dataset <span class="ot">&lt;-</span> tidy_dataset <span class="sc">%&gt;%</span></span>
<span id="cb15-12"><a href="data-prep.html#cb15-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(country <span class="sc">!=</span> <span class="st">&quot;Caribbean Netherlands&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-13"><a href="data-prep.html#cb15-13" aria-hidden="true" tabindex="-1"></a>   <span class="fu">rbind</span>(CN_subregions)  </span></code></pre></div>
</div>
</div>
<div id="prep-rmd-6.-gapfilling" class="section level2" number="3.9">
<h2><span class="header-section-number">3.9</span> prep Rmd: 6. Gapfilling</h2>
<p>We make every effort to gapfill missing data. The only legitimate reason for a region to have an NA value is if the goal is not relevant to the region. For example, the livelihoods and economies goal is not relevant for an uninhabited island.</p>
<p>We have a paper describing why and how we estimate missing data: <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0160377" class="uri">https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0160377</a>. But the following is the short version.</p>
<p>The first step to gapfilling missing data is to identify datasets that are predictive of the variable you are attempting to estimate and is also more complete. Here are some of the general approaches we use to estimate missing global data:</p>
<ul>
<li>Some missing data can be estimated from the original source. For example, if there are some missing years within a dataset, we can often estimate these values using a linear model of available data. For spatial raster data, we often estimate missing values using nearby raster cells.<br />
</li>
<li>Secondary datasets can also be used to estimate missing values. For example, we gapfill some missing Social Progress Index values using World Governance Index data as a predictor. And, in many cases we use <a href="https://github.com/OHI-Science/ohiprep_v2019/blob/gh-pages/globalprep/spatial/v2017/output/georegion_labels.csv">UN geopolitical data</a> that classifies countries based on geopolitical and social variables to predict missing data.</li>
<li>And, we often use multiple approaches to estimate missing values within a dataset.</li>
</ul>
<p>Our goal is to estimate missing data using the simplest model that best predicts the data. Given this, it is necessary to determine whether datasets and model terms actually predict missing data and to compare the performance of multiple models. Ideally cross-validation methods are used to evaluate how well the models predict missing data, otherwise models will appear to perform much better than they actually do.</p>
<p><em>There is no point in having a model with many predictive variables and complex non-linear fits if it performs no better than using a simple mean of the existing data!</em></p>
<div id="training-linear-models-for-gapfilling" class="section level3" number="3.9.1">
<h3><span class="header-section-number">3.9.1</span> Training linear models for gapfilling</h3>
<p><strong>Basic gist:</strong>
Use alternative datasets to predict data points for a dataset you have limited data points for. In this instance, we had FMI data points for 40 regions included in the OHI, and needed to gapfill the remaining 180 regions. We checked for correlation between the FMI data and several other datasets, including AO need (rescaled GDP per capita per person purchasing power), GDP per capita, social progress index (SPI), world governance indicator (WGI), and UN georegions.</p>
<p>A detailed example can be found <a href="https://github.com/OHI-Science/ohiprep_v2019/blob/gh-pages/globalprep/res_fmi/v2019/fmi_model_compare.Rmd">here</a></p>
<p><strong>Steps:</strong></p>
<ol style="list-style-type: decimal">
<li>Collect data that you’ll use to predict values, and merge with existing data (only use the values that correspond to data you already have to create this df)</li>
<li>Look at correlation between alternative data sets cor.test() and pairs.panels()</li>
<li>Create initial model:</li>
</ol>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="data-prep.html#cb16-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(dep_variable <span class="sc">~</span> ind_variable, <span class="at">data=</span>df_name)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Look at <code>summary(mod1)</code> to check for R-squared and p-value</li>
<li>Create an array of predicted values:</li>
</ol>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="data-prep.html#cb17-1" aria-hidden="true" tabindex="-1"></a>df_predicted <span class="ot">&lt;-</span> df_name <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="data-prep.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(rgn_id) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="data-prep.html#cb17-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">do</span>({</span>
<span id="cb17-4"><a href="data-prep.html#cb17-4" aria-hidden="true" tabindex="-1"></a>    pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, <span class="at">newdata =</span>.[<span class="fu">c</span>(<span class="st">&#39;ind_variable&#39;</span>)]) <span class="co"># creates a new column for predicted values</span></span>
<span id="cb17-5"><a href="data-prep.html#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(., fmi_pred) <span class="co"># do loop applies the model fitting and prediction to each country group</span></span>
<span id="cb17-6"><a href="data-prep.html#cb17-6" aria-hidden="true" tabindex="-1"></a>    }) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="data-prep.html#cb17-7" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">ungroup</span>()</span></code></pre></div>
<ol start="6" style="list-style-type: decimal">
<li>Plot predicted vs actual values:</li>
</ol>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="data-prep.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(<span class="fu">ggplot</span>(df_predicted, <span class="fu">aes</span>(<span class="at">x =</span> dep_variable, <span class="at">y =</span> pred, <span class="at">labels =</span> rgn_id)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="data-prep.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="data-prep.html#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>))</span></code></pre></div>
<p><em>Note: “rgn_id” is just an example of a column in the dataset with a unique value for each observation.</em></p>
<p>lm() can also include multiple independent variables (must be merged into one data frame with one row for each observation):
mod2 &lt;- lm(dep_variable ~ ind_variable + ind_variable2, data=df_name)</p>
<ol start="7" style="list-style-type: decimal">
<li><p>Compare models for fit and degrees of freedom: <code>AIC(mod1, mod2)</code></p></li>
<li><p>Use best-fit model to gapfill areas without data using do loop as shown in step 4.</p></li>
</ol>
<p>If using UN georegions to gapfill, you’ll want to use the most specific/granular label possible. Use separate models for regional and continental levels (r2_label vs r1_label as described in metadata above), and write code to tell R to grab the data from the most granular data available. Example from <a href="https://github.com/OHI-Science/ohiprep_v2019/blob/gh-pages/globalprep/res_fmi/v2019/fmi_model_compare.Rmd">FMI model comparison .Rmd</a>:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="data-prep.html#cb19-1" aria-hidden="true" tabindex="-1"></a>fmi_gf_all <span class="ot">&lt;-</span> fmi_gf1 <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="data-prep.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(fmi_gf2, <span class="at">by=</span><span class="fu">c</span>(<span class="st">&quot;rgn_id&quot;</span>, <span class="st">&quot;r1_label&quot;</span>, <span class="st">&quot;r2_label&quot;</span>, <span class="st">&quot;rgn_label&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;spi&quot;</span>, <span class="st">&quot;fmi&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="data-prep.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gapfilled =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(fmi) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(fmi_pred_r2), <span class="st">&quot;1&quot;</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="data-prep.html#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">method =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(fmi) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(fmi_pred_r2), <span class="st">&quot;SPI + UN_geopolitical region r2&quot;</span>, <span class="cn">NA</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="data-prep.html#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fmi =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(fmi), fmi_pred_r2, fmi)) <span class="sc">%&gt;%</span> </span>
<span id="cb19-6"><a href="data-prep.html#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gapfilled =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(fmi) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(fmi_pred_r1), <span class="st">&quot;1&quot;</span>, gapfilled)) <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="data-prep.html#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">method =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(fmi) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(fmi_pred_r1), <span class="st">&quot;SPI + UN_geopolitical region r1&quot;</span>, method)) <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="data-prep.html#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fmi =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(fmi), fmi_pred_r1, fmi))</span></code></pre></div>
</div>
<div id="saving-gapfilling-report-files" class="section level3" number="3.9.2">
<h3><span class="header-section-number">3.9.2</span> Saving gapfilling report files</h3>
<p>Gapfilling steps are often mixed with the dataprep code. Once the gapfilling is done, we will save a dataset describing which data were gapfilled and the method. Every dataset should have a corresponding gapfilling dataset…<em>even if there was no gapfilling</em>.</p>
<p>The gapfilling record is saved with the same name as the corresponding output data, but with a “_gf” extension.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vTGj33cUjqLbPw3sPkPBNGovaaradQASn3CzuTvLL8VgcFqcmlPGNskPksNjlqu1E8enu9zVSOklXJ8/pub?w=960&amp;h=720" /></p>
<p>The gapfilling dataset should mirror the corresponding dataset in regard to the number of rows and identifying columns (e.g., rgn_id, commodity, year, etc.). The gapfilling datset should include three additional columns that indicate the following:</p>
<ul>
<li>gapfilled: a zero or one value (or, NA if the value in the original data is NA) indicating whether the data was gapfilled or not.</li>
<li>method: a short descriptor of the method that was used (this should be described more fully somewhere in the documentation).</li>
<li>error: a numeric value describing the error around the estimate. This should be left blank if this was not determined (most of the time this will not be estimated).</li>
</ul>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vSFPuVZaRrO__JnOOSOl-AukPo3HN3rpBcIYDuC0pau2xHw3IVtnqOvTrdY5AfcVs7XybADvZD-tLtr/pub?w=691&amp;h=690" /></p>
</div>
</div>
<div id="prep-rmd-7.-results-check" class="section level2" number="3.10">
<h2><span class="header-section-number">3.10</span> prep Rmd: 7. Results check</h2>
<p>It is critical to check the final output data!</p>
<p>Here are some of the ways we check data:</p>
<ul>
<li>Is each region included in the final data?</li>
<li>Does the number of values for each region/year make sense (in most cases there should only be one value for each region/year)</li>
<li>Does the ranking of the values make sense? Do the high and low performing regions seem reasonable?</li>
<li>Do the number of NA values seem reasonable (ideally there will be none, unless the goal does not apply to that region)</li>
<li>Does the range/distribution of values seem reasonable, for example, some outputs should range from 0-1.</li>
</ul>
<p>The functions I use most commonly to check data are:
<code>hist()</code>, <code>summary()</code>, <code>dim()</code>, <code>table()</code></p>
<p>Because we calculate the global index every year, the most powerful way of checking our data is to compare the current data with last year’s data. In most cases, source data will remain the same from year to year (although some agencies will update previous data). Consequently, any changes will often reflect changes to the model and/or mistakes.</p>
<p>For this comparison we typically compare the most recent shared year of data between the two assessments. The following code walks through this process using data calculated for the lasting special places goal. In this case, we will pretend we have just completed preparing the data for the 2018 assessment and we want to compare the results to the 2017 assessment. Here we focus on the data for the 3nm offshore region.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="data-prep.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb20-2"><a href="data-prep.html#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb20-3"><a href="data-prep.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb20-4"><a href="data-prep.html#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb20-5"><a href="data-prep.html#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="data-prep.html#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># want the region data from here:</span></span>
<span id="cb20-7"><a href="data-prep.html#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;http://ohi-science.org/ohiprep_v2019/workflow/R/common.R&#39;</span>)</span>
<span id="cb20-8"><a href="data-prep.html#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="data-prep.html#cb20-9" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">&quot;globalprep/lsp/v2018/output/lsp_prot_area_offshore3nm.csv&quot;</span>))</span>
<span id="cb20-10"><a href="data-prep.html#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(new)</span>
<span id="cb20-11"><a href="data-prep.html#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="data-prep.html#cb20-12" aria-hidden="true" tabindex="-1"></a>old <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">&quot;globalprep/lsp/v2017/output/lsp_prot_area_offshore3nm.csv&quot;</span>))</span>
<span id="cb20-13"><a href="data-prep.html#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(old)</span></code></pre></div>
<p>The most recent shared year between the two datasets is 2017, so this is the year that will be compared. The old and new values are plotted as a scatterplot, with a point for each region. We create an interactive plot and add a one-to-one line to make it easier to determine which regions have changed. Any changes in values will reflect either changes to the source data or changes to the data prep script.</p>
<p><em>It is important to explore the reasons for these changes because it could reflect errors!</em></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="data-prep.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get region names</span></span>
<span id="cb21-2"><a href="data-prep.html#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">region_data</span>()</span>
<span id="cb21-3"><a href="data-prep.html#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rgns_eez)</span>
<span id="cb21-4"><a href="data-prep.html#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="data-prep.html#cb21-5" aria-hidden="true" tabindex="-1"></a>compare <span class="ot">&lt;-</span> new <span class="sc">%&gt;%</span></span>
<span id="cb21-6"><a href="data-prep.html#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">a_prot_3nm_new =</span> a_prot_3nm) <span class="sc">%&gt;%</span></span>
<span id="cb21-7"><a href="data-prep.html#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(old, <span class="at">by=</span><span class="fu">c</span>(<span class="st">&quot;rgn_id&quot;</span>, <span class="st">&quot;year&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb21-8"><a href="data-prep.html#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2017</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-9"><a href="data-prep.html#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(rgns_eez, <span class="at">by=</span><span class="st">&quot;rgn_id&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-10"><a href="data-prep.html#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rgn_id, rgn_name, year, a_prot_3nm, a_prot_3nm_new) <span class="sc">%&gt;%</span></span>
<span id="cb21-11"><a href="data-prep.html#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">region=</span><span class="fu">paste</span>(rgn_id, rgn_name, <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>))</span>
<span id="cb21-12"><a href="data-prep.html#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="data-prep.html#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(compare)</span>
<span id="cb21-14"><a href="data-prep.html#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="data-prep.html#cb21-15" aria-hidden="true" tabindex="-1"></a>compare_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(compare, <span class="fu">aes</span>(<span class="at">x=</span>a_prot_3nm, <span class="at">y=</span>a_prot_3nm_new, <span class="at">label=</span>region)) <span class="sc">+</span></span>
<span id="cb21-16"><a href="data-prep.html#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-17"><a href="data-prep.html#cb21-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="dv">1</span>, <span class="at">intercept=</span><span class="dv">0</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb21-18"><a href="data-prep.html#cb21-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-19"><a href="data-prep.html#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(compare_plot)</span></code></pre></div>
<p>In this case, the values for most regions remain the same from the 2017 to 2018 assessment, however, there are some changes. The biggest change was for Antarctica, which we can ignore because we do not calculate scores for Antarctica for the global assessment. However, there is also a fairly large change in the Greece data, and some smaller changes for some other regions.</p>
<p>By carefully exploring the source data we found that these differences reflect updates to the source data. For example, a marine reserve may have been established in 2017, but weren’t yet incorporated into the World Database on Protected Areas.</p>
</div>
<div id="prep-rmd-8.-final-run" class="section level2" number="3.11">
<h2><span class="header-section-number">3.11</span> prep Rmd: 8. Final run</h2>
<p>The final step is to commit and push all files. Then, close R and do NOT save the workspace image. The purpose of closing everything is to clear the memory of all data objects to make sure that the code still runs. This may be a problem if we change object names but fail to make necessary corresponding throughout the code.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vRf6bzIscOnKcqrxUNn9q4IOkPbElNbCJbcXpb3oC6jADbeVQ-e4pAA17fUBYa3GiJENILw48xgBSA4/pub?w=531&amp;h=243" /></p>
<p>I typically close everything by opening another repository.</p>
<p>Restart R and return to the ohiprep repo and rerun everything (except any really long processes).</p>
<p>Check the following:</p>
<ul>
<li>Does all the code still run?</li>
<li>Do you get the same results (check to see if output csv files are loaded to the Git window, this indicates that the data probably changed)?</li>
<li>Review warnings</li>
<li>Identify parts of the code you are unsure of, and have someone review</li>
</ul>
<hr />
</div>
<div id="notes-on-parallel-processing" class="section level2" number="3.12">
<h2><span class="header-section-number">3.12</span> Notes on parallel processing</h2>
<p>In OHI, we often use parallel processing packages to process data-intensive spatial layers. Parallel processing allows multiple computations to take place at the same time. For more information, check out this <a href="https://nceas.github.io/oss-lessons/parallel-computing-in-r/parallel-computing-in-r.html">introductory resource from NCEAS.</a></p>
<p><em>Note: below is essentially copy and pasted from <a href="https://github.com/OHI-Science/globalfellows-issues/issues/43">this reference issue</a> and might need more context to be helpful</em></p>
<p><a href="https://cran.r-project.org/web/packages/doParallel/vignettes/gettingstartedParallel.pdf">Vignette on getting started with doParallel and foreach packages</a> refers to two ways to use parallel processing in the <code>doParallel</code> package.</p>
<p><em>Method 1:</em> <code>registerDoParallel(4)</code></p>
<p>OR</p>
<p><em>Method 2:</em></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="data-prep.html#cb22-1" aria-hidden="true" tabindex="-1"></a>cl <span class="ot">&lt;-</span> <span class="fu">makeCluster</span>(<span class="dv">4</span>)</span>
<span id="cb22-2"><a href="data-prep.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoParallel</span>(cl)</span>
<span id="cb22-3"><a href="data-prep.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">foreach</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>) <span class="sc">%dopar%</span>{}</span>
<span id="cb22-4"><a href="data-prep.html#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopCluster</span>(cl)</span></code></pre></div>
<div id="stopcluster-makecluster" class="section level3" number="3.12.1">
<h3><span class="header-section-number">3.12.1</span> stopCluster &amp; makeCluster</h3>
<p><strong>Stopping your cluster:</strong></p>
<p>If you are using snow-like functionality, you will want to stop your cluster when you are done using it. The doParallel package’s .onUnload function will do this automatically if the cluster was created automatically by registerDoParallel, but if you created the cluster manually you should stop it using the stopCluster function: <code>stopCluster(cl)</code></p>
<p><a href="https://stackoverflow.com/questions/45894635/why-does-doparallelgetdoparworkers-return-14-but-after-i-have-completed-the">Stack overflow discussion</a> on whether cores stop being registered after <code>foreach</code> finishes</p>
<p><strong>Tip:</strong> Limit to 5 or fewer cores for any data prep</p>
</div>
<div id="using-htop-to-check-on-processes-running" class="section level3" number="3.12.2">
<h3><span class="header-section-number">3.12.2</span> Using htop to check on processes running</h3>
<p>Sometimes a process will be running that slows down the whole system, and htop can help identify and stop the source of this issue.</p>
<p><a href="https://www.deonsworld.co.za/2012/12/20/understanding-and-using-htop-monitor-system-resources/">Useful resource here</a></p>
<ol style="list-style-type: decimal">
<li><p>When you are logged into the Mazu RStudio server window, open the terminal shell.</p></li>
<li><p>type <code>htop</code> and hit enter
<img src="https://docs.google.com/drawings/d/e/2PACX-1vTTRgierwPuguYyuVRQIepMIKtUq1HWYzju-vtW2BjUOtuYD24PMx3Y6s6CsZNmbwu27rtqrQa6y5Tw/pub?w=300&amp;h=100" /></p></li>
<li><p>When you press enter, a matrix will appear showing how many cores are being used, and the processes running underneath</p></li>
</ol>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vSXapuGRUlSxvW32xW74lU-Iv9p5eikiQixj93hfIeM0ivozG6hwsIjZO6q2f_l7NkHt5AM-73jMFO6/pub?w=910&amp;h=463" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Kill processes by scrolling with arrow keys or by clicking on them. Click ‘kill’ or hit k on the keyboard</li>
</ol>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vTw7iG5UPirTfqJkqSn96FdO-3hzcrJhJN5xmi1RilGW4EysFnBC4ADi7B_NlaeuIGDNlwMEKKxV_F9/pub?w=212&amp;h=100" /></p>
<ol start="5" style="list-style-type: decimal">
<li>‘Send signal’ bar will open with 15 SIGTERM highlighted - hit enter, or esc to cancel</li>
</ol>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vQbUM7vh3GTXqgOduYhFWdrbJ2ATZXtkxpyTo2dr1j8RF82t76_WHPxcBdaIceHmcYLnzvatEVg_XiW/pub?w=337&amp;h=641" /></p>
<p>Note: some users have problems with RStudio crashing when trying to kill processes in the terminal window. Using the terminal on your computer should work with no problem. To do this, open the terminal and login using <code>ssh username@mazu.nceas.ucsb.edu</code> and hit enter. Enter your password (letters will not appear) and hit enter to login, then follow the steps above.</p>
<p><img src="https://docs.google.com/drawings/d/e/2PACX-1vT3gCYjGdUl3SEh03V7UasbtqBin5TKyPVKdssJDA8ybz4J6ZYitDuMof70F50yaCjyDa8t50J4kYlp/pub?w=596&amp;h=120" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="starting-a-new-year.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="updating-scores.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/OHI-Science/ohi-global-guide/edit/master/data_prep.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["series.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
